/* tslint:disable */
/* eslint-disable */
/**
 * openapi quirks documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Animal } from "./Animal";
import { AnimalFromJSON, AnimalFromJSONTyped, AnimalToJSON } from "./Animal";

/**
 *
 * @export
 * @interface Fish
 */
export interface Fish extends Animal {}

/**
 * Check if a given object implements the Fish interface.
 */
export function instanceOfFish(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function FishFromJSON(json: any): Fish {
  return FishFromJSONTyped(json, false);
}

export function FishFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Fish {
  return json;
}

export function FishToJSON(value?: Fish | null): any {
  return value;
}
