/* tslint:disable */
/* eslint-disable */
/**
 * openapi quirks documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MammalAllOf
 */
export interface MammalAllOf {
  /**
   *
   * @type {string}
   * @memberof MammalAllOf
   */
  classTypicalBreedingSize?: string;
}

/**
 * Check if a given object implements the MammalAllOf interface.
 */
export function instanceOfMammalAllOf(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function MammalAllOfFromJSON(json: any): MammalAllOf {
  return MammalAllOfFromJSONTyped(json, false);
}

export function MammalAllOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MammalAllOf {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    classTypicalBreedingSize: !exists(json, "classTypicalBreedingSize")
      ? undefined
      : json["classTypicalBreedingSize"],
  };
}

export function MammalAllOfToJSON(value?: MammalAllOf | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    classTypicalBreedingSize: value.classTypicalBreedingSize,
  };
}
