/* tslint:disable */
/* eslint-disable */
/**
 * openapi quirks documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Animal,
} from '../models';
import {
    AnimalFromJSON,
    AnimalToJSON,
} from '../models';

/**
 * 
 */
export class BoundaryApi extends runtime.BaseAPI {

    /**
     * Retrieves all actions
     * Finds all Actions
     */
    async listAnimalsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Animal>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/boundary/muahaha`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AnimalFromJSON));
    }

    /**
     * Retrieves all actions
     * Finds all Actions
     */
    async listAnimals(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Animal>> {
        const response = await this.listAnimalsRaw(initOverrides);
        return await response.value();
    }

}
