/* tslint:disable */
/* eslint-disable */
/**
 * openapi quirks documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Animal,
    AnimalFromJSON,
    AnimalFromJSONTyped,
    AnimalToJSON,
} from './';

/**
 * 
 * @export
 * @interface Fish
 */
export interface Fish extends Animal {
}

export function FishFromJSON(json: any): Fish {
    return FishFromJSONTyped(json, false);
}

export function FishFromJSONTyped(json: any, ignoreDiscriminator: boolean): Fish {
    return json;
}

export function FishToJSON(value?: Fish | null): any {
    return value;
}

