/* tslint:disable */
/* eslint-disable */
/**
 * openapi quirks documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Animal,
    AnimalFromJSON,
    AnimalFromJSONTyped,
    AnimalToJSON,
} from './';

/**
 * 
 * @export
 * @interface Mammal
 */
export interface Mammal extends Animal {
    /**
     * 
     * @type {string}
     * @memberof Mammal
     */
    classTypicalBreedingSize: string;
}

export function MammalFromJSON(json: any): Mammal {
    return MammalFromJSONTyped(json, false);
}

export function MammalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mammal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...AnimalFromJSONTyped(json, ignoreDiscriminator),
        'classTypicalBreedingSize': json['classTypicalBreedingSize'],
    };
}

export function MammalToJSON(value?: Mammal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...AnimalToJSON(value),
        'classTypicalBreedingSize': value.classTypicalBreedingSize,
    };
}

